extends:
  - standard
  - eslint:recommended
rules:
  semi: ['error', 'never']
  no-multiple-empty-lines: [error, {"max": 3, "maxEOF": 1}]
  no-trailing-spaces: error
  comma-dangle: ['error', 'always-multiline']
  no-var: error
  generator-star-spacing: ['error', {before: false, after: true}]
  yield-star-spacing: ['error', {before: false, after: true}]
  require-yield: off
