extends:
  - eslint:recommended
  - standard
env:
  node: false
rules:
  semi: [error, never]
  no-multiple-empty-lines: [error, {max: 3, maxEOF: 0}]
  no-trailing-spaces: error
  comma-dangle: ['error', 'always-multiline']
  no-use-before-define: [error, {functions: false, classes: false}]
  no-unused-vars: [error, {
    vars: 'all',
    args: 'all',
    argsIgnorePattern: '^_'
  }]
  # ES6
  no-var: error
  arrow-parens: error
  no-useless-rename: error
  prefer-rest-params: error
  prefer-spread: error
  generator-star-spacing: ['error', {before: false, after: true}]
  yield-star-spacing: ['error', {before: false, after: true}]
  require-yield: off
